### ISSUE TITLE
Problem with latest release (aliases) ... 

### ISSUE THREAD

**Issue by andreasprlic** [biocommons/biocommons.seqrepo#134] opened 2024-01-19 22:42 UTC
**Describe the bug**
I tried to upgrade to the latest release today and the aliases do not seem to work correctly for me on OSX:

**To Reproduce**
I ran the following steps:
```
sudo mkdir -p /usr/local/share/seqrepo
sudo chown $USER /usr/local/share/seqrepo
seqrepo pull -i 2023-09-18
```

Then the command `seqrepo show-status -i  2023-09-18` results with:

```
seqrepo 0.6.6
instance directory: /usr/local/share/seqrepo/2023-09-18, 12.6 GB
backends: fastadir (schema 1), seqaliasdb (schema 1)
sequences: 1143428 sequences, 125510353291 residues, 429 files
Traceback (most recent call last):
  File "/Users/andreas.prlic/WORK/GIT/variant_registration/.venv/bin/seqrepo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/andreas.prlic/WORK/GIT/variant_registration/.venv/lib/python3.11/site-packages/biocommons/seqrepo/cli.py", line 732, in main
    opts.func(opts)
  File "/Users/andreas.prlic/WORK/GIT/variant_registration/.venv/lib/python3.11/site-packages/biocommons/seqrepo/cli.py", line 595, in show_status
    sa=sr.aliases.stats()
       ^^^^^^^^^^^^^^^^^^
  File "/somewhere/.venv/lib/python3.11/site-packages/biocommons/seqrepo/seqaliasdb/seqaliasdb.py", line 164, in stats
    cursor.execute(sql)
sqlite3.DatabaseError: database disk image is malformed
```

**Expected behavior**
I would expect this to print something similar to:
```
seqrepo show-status -i  2020-11-27
seqrepo 0.6.6
instance directory: /usr/local/share/seqrepo/2020-11-27, 12.1 GB
backends: fastadir (schema 1), seqaliasdb (schema 1)
sequences: 947937 sequences, 124726644320 residues, 409 files
aliases: 4776535 aliases, 4776535 current, 35 namespaces, 947937 sequences
```

**Additional context**

**Comment by jsstevenson** [comment] 2024-01-22 01:36
yup

```shell
sqlite3 /usr/local/share/seqrepo/2023-09-18/aliases.sqlite3 'PRAGMA integrity_check;' | wc -l  # returns 101
```

**Comment by reece** [comment] 2024-02-21 02:11
Duplicate of #126. Closing, but see there for update from today.

**Closed by reece** 2024-02-21 02:11 UTC
Labels: bug
