### ISSUE TITLE
Database file problem with 2023-09-18 snapshot

### ISSUE THREAD

**Issue by ehclark** [biocommons/biocommons.seqrepo#126] opened 2023-12-15 20:45 UTC
There appears to be some corruption in the 2023-09-18 snapshot.  The `show-status` command exits with a `sqlite3.DatabaseError: database disk image is malformed` message and some of the aliases that should be present in the database are not found.  But seqrepo to function normally, aside from the missing aliases.  I noticed this when trying to run the unit tests for AnyVar, which fail due to the missing alias problem.  The 2021-01-29 snapshot does not have the same issues.  See observed outputs below:

# Get the fresh copies of both snapshots
```bash
$ rsync -HavP dl.biocommons.org::seqrepo/2023-09-18 2023-09-18/
$ rsync -HavP dl.biocommons.org::seqrepo/2021-01-29 2021-01-29/
```

# Run show-status on each
```bash
$ docker run -it --rm -v $(pwd):/usr/local/share/seqrepo biocommons/seqrepo:latest seqrepo show-status -i 2021-01-29
seqrepo 0.6.6
instance directory: /usr/local/share/seqrepo/2021-01-29, 12.1 GB
backends: fastadir (schema 1), seqaliasdb (schema 1) 
sequences: 949078 sequences, 124734762509 residues, 411 files
aliases: 4782812 aliases, 4782812 current, 35 namespaces, 949078 sequences

$ docker run -it --rm -v $(pwd):/usr/local/share/seqrepo biocommons/seqrepo:latest seqrepo show-status -i 2023-09-18
seqrepo 0.6.6
instance directory: /usr/local/share/seqrepo/2023-09-18, 12.6 GB
backends: fastadir (schema 1), seqaliasdb (schema 1) 
sequences: 1143428 sequences, 125510353291 residues, 429 files
Traceback (most recent call last):
  File "/usr/local/bin/seqrepo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/cli.py", line 732, in main
    opts.func(opts)
  File "/usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/cli.py", line 595, in show_status
    sa=sr.aliases.stats()
  File "/usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/seqaliasdb/seqaliasdb.py", line 164, in stats
    cursor.execute(sql)
sqlite3.DatabaseError: database disk image is malformed
```

# Run the shell and query for aliases
```bash
$ docker run -it --rm -v $(pwd):/usr/local/share/seqrepo biocommons/seqrepo:latest seqrepo start-shell -i 2021-01-29
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.


seqrepo (https://github.com/biocommons/biocommons.seqrepo/)
version: 0.6.6
instance path: /usr/local/share/seqrepo/2021-01-29

In [1]: sr["NC_000010.11"]
Out[1]: SequenceProxy(seq_id=ss8r_wB0-b9r44TQTMmVTI92884QvBiB, len=133797422)

In [2]: sr["refseq:NC_000010.11"]
Out[2]: SequenceProxy(seq_id=ss8r_wB0-b9r44TQTMmVTI92884QvBiB, len=133797422)

In [3]: exit

$ docker run -it --rm -v $(pwd):/usr/local/share/seqrepo biocommons/seqrepo:latest seqrepo start-shell -i 2023-09-18
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.


seqrepo (https://github.com/biocommons/biocommons.seqrepo/)
version: 0.6.6
instance path: /usr/local/share/seqrepo/2023-09-18

In [1]: sr["NC_000010.11"]
Out[1]: SequenceProxy(seq_id=ss8r_wB0-b9r44TQTMmVTI92884QvBiB, len=133797422)

In [2]: sr["refseq:NC_000010.11"]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[2], line 1
----> 1 sr["refseq:NC_000010.11"]

File /usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/seqrepo.py:153, in SeqRepo.__getitem__(self, nsa)
    151 ns, a = nsa.split(nsa_sep) if nsa_sep in nsa else (None, nsa)
    152 if self.use_sequenceproxy:
--> 153     return SequenceProxy(self, alias=a, namespace=ns)
    154 else:
    155     return self.fetch(alias=a, namespace=ns)

File /usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/seqrepo.py:36, in SequenceProxy.__init__(self, sr, namespace, alias)
     34 def __init__(self, sr, namespace, alias):
     35     self._sr = sr
---> 36     self.seq_id = sr._get_unique_seqid(alias=alias, namespace=namespace)
     37     self._md = sr.sequences.fetch_seqinfo(self.seq_id)

File /usr/local/lib/python3.10/dist-packages/biocommons/seqrepo/seqrepo.py:324, in SeqRepo._get_unique_seqid(self, alias, namespace)
    322 seq_ids = set(r["seq_id"] for r in recs)
    323 if len(seq_ids) == 0:
--> 324     raise KeyError("Alias {} (namespace: {})".format(alias, namespace))
    325 if len(seq_ids) > 1:
    326     # This should only happen when namespace is None
    327     raise KeyError("Alias {} (namespace: {}): not unique".format(alias, namespace))

KeyError: 'Alias NC_000010.11 (namespace: refseq)'

In [3]: exit
```

**Comment by reece** [comment] 2024-02-20 03:37
Confirmed. That snapshot appears to be broken. I'm looking into it now.

**Comment by reece** [comment] 2024-02-20 03:44
Sigh. It looks like this was pushed in a rush during the hackathon and is broken. I think the only course is going to be to reload sequences.

**Comment by reece** [comment] 2024-02-20 16:54
I've restarted loading a new seqrepo release. ETA is a day or two.

**Comment by reece** [comment] 2024-02-20 16:57
BTW, @ehclark, thanks for your very thorough bug report! Very helpful!

**Comment by reece** [comment] 2024-02-20 21:33
A new (and working!) seqrepo collection is out.

```
snafu$ seqrepo pull
receiving incremental file list
created directory /usr/local/share/seqrepo/2024-02-20.1y6fal7j
./
aliases.sqlite3
  1,571,753,984 100%   18.80MB/s    0:01:19 (xfr#1, ir-chk=1004/1006)
sequences/
sequences/db.sqlite3
    246,669,312 100%   21.78MB/s    0:00:10 (xfr#2, ir-chk=1008/1012)
sequences/2024/
⋮

snafu$ seqrepo -r /usr/local/share/seqrepo/ show-status -i 2024-02-20
seqrepo 0.6.9
instance directory: /usr/local/share/seqrepo/2024-02-20, 13.5 GB
backends: fastadir (schema 1), seqaliasdb (schema 1) 
sequences: 1143253 sequences, 128791847751 residues, 432 files
aliases: 5860851 aliases, 5860851 current, 35 namespaces, 1143253 sequences

snafu$ seqrepo -r /usr/local/share/seqrepo/ show-status -i 2021-01-29
seqrepo 0.6.9
instance directory: /usr/local/share/seqrepo/2021-01-29, 12.1 GB
backends: fastadir (schema 1), seqaliasdb (schema 1) 
sequences: 949078 sequences, 124734762509 residues, 411 files
aliases: 4782812 aliases, 4782812 current, 35 namespaces, 949078 sequences

```

That's 194175 new sequences (about a 20% increase).

I would appreciate confirmation and closing this issue if resolved.

**Comment by andreasprlic** [comment] 2024-02-21 04:08
Downloaded the latest version on my system, and this looks good to me now.

**Closed by andreasprlic** 2024-02-21 04:08 UTC
Labels: bug
